name: Build and Deploy Pelican site

on:
  push:
    branches:
      - main  # or master if that's your default branch

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Pelican and ghp-import
        run: |
          python -m pip install --upgrade pip
          pip install pelican[markdown] ghp-import

      - name: Build site
        run: make publish

      - name: Deploy to GitHub Pages
        run: |
          ghp-import output -b gh-pages
          git push -f https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} gh-pages
